name : chocolatine

on:
  push:
    branches-ignore:
     - 'ga-ignore-**'
  pull_request:
    branches-ignore:
     - 'ga-ignore-**'

env:
  MIRROR_URL: "git@github.com:Philou699/BSQ-biggest-square.git"
  EXECUTABLES: bsq

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - name: "Checkout repository coding style."
        run: |
          check.sh $(pwd) $(pwd);
          if [[-s coding-style-reports.log]];
            then
              echo "Coding Style Errors: ";
              cat coding-style-reports.log;
              exit 1;
          fi
          echo "Repository is clean !";
          exit 0;

check_program_compilation:
  name: "Checks if the program compiles correctly."
  runs-on: ubuntu-latest
  container: 
    image: epitechcontent/epitest-docker:latest
  needs: 
    - check_coding_style
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
    - run: make
      timeout-minutes: 2
    - run: make clean
      run: |
        OIFS=$IFS
        IFS=','
        for x in $EXECUTABLES
          do
            ./$x
          done
        IFS=$OIFS

    - name: Fail if needed
      if: env.FAIL_TASK == 'true'
      run: exit 1

run_tests:
  name: "Run the criterion program tests."
  runs-on: ubuntu-latest
  needs: [check_compilation]
  container: 
    image: epitechcontent/epitest-docker:latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Starts tests
    - id: run_tests
      run: make tests_run
      timeout-minutes: 2

  push_to_mirror:
    name: Pushes the current repository files to a given mirror repository
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push mirror repository
        uses: pixta-dev/repository-mirroring-action@main
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}